#!/bin/bash 
if [ $1 = "-f" ]; then
    racket ../../python-compiler/pylex.zo --exp < $2 | ./pyparse
elif [ $1 = "-fe" ]; then
    racket ../../python-compiler/pylex.zo < $2 | grep -v ENDMARKER |  ./pyparse
else
    echo $@ | racket ../../python-compiler/pylex.zo --exp | ./pyparse
fi
